#!/usr/bin/env sh
set -e  # <-- stop the hook if any command fails

echo "🧪 Running tests..."
npm test

echo "🧹 Running lint-staged..."
npx lint-staged
# make this on every code change in this file
# chmod +x .husky/pre-commit
